config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'superpowers#landing'

  resources :superpowers do
    resources :bookings, only: [:new, :create]
    end

  resources :superpowers do
    resources :reviews, only: [ :new, :create, :edit]
  end
  resources :bookings, only: :destroy

  get 'reservation/validate', to: 'superpowers#reservation'

  resources :reviews, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :superpower
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :superpower
  validates :content, presence: true
end

app/models/superpower.rb
class Superpower < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :delete_all
  has_many :reviews, dependent: :delete_all
  has_many_attached :photos

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name,
                    against: [ :name ],
                    using: { tsearch: { prefix: true } }


def is_available?(start_date, end_date)
  bookings.each do |b|
    return false if (b.starts_at..b.ends_at).overlaps?(start_date.to_date..end_date.to_date)
  end
  true
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :superpowers
  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @superpower = Superpower.find(params[:superpower_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @superpower = Superpower.find(params[:superpower_id])
    @booking.superpower = @superpower
    @booking.user = current_user
    @booking.save
  end

  def destroy
    @booking = booking.find(params[:id])
    @booking.destroy
    redirect_to superpowers_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :superpower_id, :starts_at, :ends_at)
  end
end

app/controllers/reviews_controller.rb
  class ReviewsController < ApplicationController

    def new
      @superpower = Superpower.find(params[:superpower_id])
      @review = Review.new
    end


    def create
      @review = Review.new(review_params)
      @superpower = Superpower.find(params[:superpower_id])
      @review.superpower = @superpower
      if @review.save
        redirect_to superpower_path(@superpower)
      else
        render new
      end
    end

    def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to superpowers_path(@Reviews)
    end

    private

    def review_params
      params.require(:review).permit(:content)
    end
  end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController
  before_action :set_superpower, only: [:update, :edit, :show, ]

  def index
    if params[:search].present?
      @superpowers = Superpower.search_by_name(params[:search])
    else
      @superpowers = Superpower.all
    end
    if params[:min_price].present?
      @superpowers = @superpowers.where("price >= ?", params[:min_price])
    end
    if params[:max_price].present?
      @superpowers = @superpowers.where("price <= ?", params[:max_price])
    end
    if params[:name].present?
      @superpowers = @superpowers.where(name: params[:name])
    end
    if params[:starts_at].present? && params[:ends_at].present?
      @superpowers = @superpowers.select do |superpower|
        superpower.is_available?(params[:starts_at], params[:ends_at])
      end
    end
  end

  def show
    @booking = Booking.new
    @bookings_dates = @superpower.bookings.map do |booking|
      {
        from: booking.starts_at,
        to: booking.ends_at
      }
    end
    @review = Review.new
  end

  def new
    @superpower = Superpower.new
  end

  def create
    @superpower = Superpower.new(superpower_params)
    @superpower.user = current_user

    if @superpower.save

      redirect_to superpower_path(@superpower)

    else
      render :new
    end
  end

  def edit
  end

  def update
    @superpower.update(superpower_params)
    redirect_to superpower_path(@superpower)
  end

  def destroy
    @superpower = Superpower.find(params[:id])
    @superpower.destroy
    redirect_to superpowers_path(@superpowers)
  end

  private

  def set_superpower
    @superpower = Superpower.find(params[:id])
  end

  def superpower_params
    params.require(:superpower).permit(:name, :description, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/superpowers_helper.rb
module SuperpowersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperPnP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload", defer: true %>
  </head>
  <body>
      <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<%= simple_form_for [ @superpower, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Ajoutes un commentaire", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_topnavbar.html.erb
<div class="topnavbar">

    <div class="left col-4">

      <ul class="text_left">

        <li><a href="<%= superpowers_path %>">Home</a></li>
        <li><a href="<%= new_superpower_path %>">Rent</a></li>
      </ul>
    </div>
    <div class="logo col-4">
      <%= image_tag("logo.png", :class =>"style_logo") %>
    </div>
    <div class="right col-4">
      <ul>
        <li><%= image_tag("batman.jpg", :class => "style_user_picture") %></li>
        <% if user_signed_in? %>
          <li class="logout" style="margin-top: 25px;"><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="<%= new_user_session_path %>">Login</a></li>
         <% end %>
      </ul>
    </div>
</div>

app/views/superpowers/_form.html.erb
 <div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Rent my superpower</h3>
        <%= simple_form_for @superpower do |f| %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.submit class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/superpowers/edit.html.erb
<%= render 'shared/topnavbar' %>
<h1> Edit your superpower ⚡️</h1>
<%= render "form", superpower: @superpower %>

app/views/superpowers/index.html.erb
<%= render 'shared/topnavbar' %>
<br>
<h1>All superpowers</h1>
<div>
  <div>
<br>
  <div class ="search-bar-container" >
    <div class="search-form">

      <%= simple_form_for :search, method: :get,
        defaults: { required: false } do |f| %>
        <div class ="searchstylecontainer">
          <div class="searchstyle">
            <%= f.input :search, placeholder: 'Which power do you want?',
            input_html: { name: 'search',
            value: params.dig(:search) } %>
          </div>
          <div class="pricestyle">
            <%= f.input :min_price, placeholder: 'Min',
              required: false,
              input_html: { type: :number,
              name: :min_price,
              value: params.dig(:min_price) } %>
            <%= f.input :max_price, placeholder: "Max",
              required: false,
              input_html: { type: :number,
              name: :max_price,
              value: params.dig(:max_price) } %>
            </div>
            <div class="datestyle">
              <%= f.input :starts_at, place: "Start at",
                  input_html: { type: :date,
                                name: :starts_at,
                                value: params.dig(:starts_at) } %>
              <%= f.input :ends_at, label: "End at",
                  input_html: { type: :date,
                                name: :ends_at,
                                value: params.dig(:ends_at) } %>
            </div>
  </div>

            <div class= "search_bar_button">
              <%= f.submit "Searching", class: "btnsearch" %>
                <% end %>
              <%= link_to "Clear filters", superpowers_path, class: "btnclear"%>
            </div>
      </div>

  <div class = "text-part">
    <p> " Become the super-hero you always wanted ! " </p>
  </div>
</div>

<div  class="container">
    <div class="cards-container">
      <% @superpowers.each do |superpower| %>
        <div class="card-trip">
         <%= link_to superpower_path(superpower) do %>
            <% if superpower.photos.attached? %>
              <%= cl_image_tag superpower.photos.first.key, height: 300, width: 400, crop: :fill %>
            <% else %>
              <%= image_tag "superpower.jpg" %>
            <% end %>
          <% end %>

          <div class="card-trip-infos">
              <h3 id=color><%= superpower.name%></h3>
              <h3 class="card-trip-pricing"><%= superpower.price %>$</h3>
              <%# class="card-trip-user avatar-bordered" %>
          </div>
        </div>
      <% end %>
    </div>
</div>

<%#
<form novalidate="novalidate" class="simple_form search" action="/superpowers" accept-charset="UTF-8" method="get" style="display: flex;">
          <div class="mb-3 string optional search_search"><label class="form-label string optional" for="search_search">Search</label><input class="form-control string optional" name="search" placeholder="Which power do you want?" type="text" id="search_search"></div>
          <div class="mb-3 string optional search_min_price"><label class="form-label string optional" for="search_min_price">Min price</label><input class="form-control string optional" type="number" name="min_price" placeholder="Minimum price" id="search_min_price"></div>
          <div class="mb-3 string optional search_max_price"><label class="form-label string optional" for="search_max_price">Max price</label><input class="form-control string optional" type="number" name="max_price" placeholder="Maximum price" id="search_max_price"></div>
          <div class="mb-3 string optional search_starts_at"><label class="form-label string optional" for="search_starts_at">Starts at</label><input class="form-control string optional" type="date" name="starts_at" id="search_starts_at"></div>
          <div class="mb-3 string optional search_ends_at"><label class="form-label string optional" for="search_ends_at">End at</label><input class="form-control string optional" type="date" name="ends_at" id="search_ends_at"></div>
            <div class="search_bar_button">
            <input type="submit" name="commit" value="Searching" class="btn btn-ghost" data-disable-with="Searching">
          <a class="btn btn-ghost" href="/superpowers">Clear filters</a>
            </div></form> %>

app/views/superpowers/landing.html.erb
    <div class="containerSP">
     <section class="stars">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </section>
        <h1 class="title">SuperPnP</h1>
        <h1 class="title2">SuperPnP</h1>
          <%= link_to superpowers_path do %>
   <%= image_tag "logoSP.png", class:"logoSP" %>
<% end %>
</div>

app/views/superpowers/new.html.erb
<%= render 'shared/topnavbar' %>


 <div class="form">
<br>
<br>
<br>
 <div class="container py-5">

  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Rent my superpower</h3>
        <%= simple_form_for @superpower do |f| %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.submit class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/superpowers/reservation.html.erb
<%= render 'shared/topnavbar' %>
<br>
<br>
<div class="container">

<div class="popup">
<button id="close">&times;</button>
  <h1>Do you feel it ?! You're a Super Hero now !</h1>
  <p>Use it well you have responsibility now</p>


</div>
</div>

app/views/superpowers/show.html.erb
<%=render 'shared/topnavbar'%>
<div class ="img_banner"></div>
<div data-controller="validate">
  <div class="popup" data-validate-target="validate">
    <h1>Do you feel it ?! You're now a Super Hero !</h1>
    <h2>Careful tho, use it well ! Like Uncle Ben said "With great Power comes great responsibility"</h2>
    <p>Your new power : <%= @superpower.name %> </p>
    <p>For : dates...</p>
    <a class ="croix "href="" data-action="click->validate#hidePopup">X</a>
  </div>
  <div class="bigbigcontainer" data-validate-target="container">
    <div class="bigcontainer">
      <div class ="superpower_card">
        <div class ="img_banner">
          <% @superpower.photos.each do |photo|%>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
        </div>
        <h1><%= @superpower.name %> </h1>
        <h2><%= @superpower.description%></h2>
        <h3><p><%= @superpower.price%> $</p></h3>
        <p class= "btn btn-secondary" >
          <%= link_to "edit", edit_superpower_url(@superpower) %> </p>
        <p class= "btn btn-secondary"> <%= link_to "delete", superpower_path(@superpower), method: :delete, data: { confirm: "Are you sure you want to delete your superpower 🧐? ", class: 'text-white'} %>
        </p>
      </div>
      <div class="bookingcontainer">
        <div class="container">
          <div class="form-wrapper">
            <%= simple_form_for [@superpower, @booking], html: { 'data-action': "submit->validate#displayPopup"} do |f| %>
            <%= f.input :starts_at, label: "Select your renting dates 📆 ",
                                    as: :string,
                                    required: false,
                                    input_html: { id: "range_start", class: "d-none"} %>
            <%= f.input :ends_at, label: false,
                                  as: :string,
                                  required: false,
                                  input_html: { id: "range_end", class: "d-none" } %>
            <%= f.button :submit, "POWER UP", class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
        <div id="booking-form-div"
            data-bookings="<%= @bookings_dates.to_json %>">
        </div>

      </div>
    </div>

    <br>
    <br>
  <hr>
<div class="col-12 col-sm-6">
    <%= pluralize @superpower.reviews.size, "Reviews" %>
    <% if @superpower.reviews.empty? %>
      <small><em class="text-muted">Be the first one to review this list</em></small>
    <% end %>
      <% @superpower.reviews.each do |review| %>
          <% review.content do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"> <hr><%= review.content %> <hr></p>
          <%= link_to "delete", review_path(review), method: :delete, data: { confirm: "Are you sure you want to remove your review? ", class: 'text-danger'} %>
        <% end %>
    </div>

    <div data-controller="popup">
      <div class="d-none" data-popup-target="modal">
        <%= simple_form_for [ @superpower, @review ] do |f| %>
          <%= f.input :content, class: "review_content"%>
          <%= f.submit "Send", class: "btn btn-ghost"%>
        <% end %>
      </div>
        <hr>
      <a href="#" data-action="click->popup#toggleModal" class= "btn btn-ghost">Add a review !</a>
    </div>

  </div>
</div>